# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'open-uri'

User.destroy_all

u1 = User.create(username: "alex", password: "password")
u2 = User.create(username: "demo-user", password: "password")

Category.destroy_all

c1 = Category.create(name: 'tanks')
c2 = Category.create(name: 'shirts')
c3 = Category.create(name: 'hoodies')
c4 = Category.create(name: 'joggers')
c5 = Category.create(name: 'hats')
c6 = Category.create(name: 'gear')

Product.destroy_all

p1 = Product.create(name: "black tank", price: 29.95, description: "100% aesthetic", category_id: c1.id)
p2 = Product.create(name: "white tank", price: 29.95, description: "100% aesthetic", category_id: c1.id)
p3 = Product.create(name: "red tank", price: 29.95, description: "100% aesthetic", category_id: c1.id)
p4 = Product.create(name: "gray tank", price: 29.95, description: "100% aesthetic", category_id: c1.id)
p5 = Product.create(name: "black stringer", price: 29.95, description: "woah woah woah", category_id: c1.id)
p6 = Product.create(name: "white stringer", price: 29.95, description: "woah woah woah", category_id: c1.id)
p7 = Product.create(name: "black cutoff", price: 29.95, description: "100% aesthetic", category_id: c1.id)
p8 = Product.create(name: "white cutoff", price: 29.95, description: "100% aesthetic", category_id: c1.id)

f1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
f2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
f3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
f4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
f5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
f6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
f7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
f8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')

f9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
f10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
f11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
f12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
f13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
f14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
f15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
f16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')

f17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
f18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
f19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
f20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
f21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
f22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
f23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
f24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')

p1.photos.attach(io: f1, filename: 'ryan.jpg')
p2.photos.attach(io: f2, filename: 'ryan.jpg')
p3.photos.attach(io: f3, filename: 'ryan.jpg')
p4.photos.attach(io: f4, filename: 'ryan.jpg')
p5.photos.attach(io: f5, filename: 'ryan.jpg')
p6.photos.attach(io: f6, filename: 'ryan.jpg')
p7.photos.attach(io: f7, filename: 'ryan.jpg')
p8.photos.attach(io: f8, filename: 'ryan.jpg')

p1.photos.attach(io: f9, filename: 'tanktop1.jpg')
p2.photos.attach(io: f10, filename: 'tanktop1.jpg')
p3.photos.attach(io: f11, filename: 'tanktop1.jpg')
p4.photos.attach(io: f12, filename: 'tanktop1.jpg')
p5.photos.attach(io: f13, filename: 'tanktop1.jpg')
p6.photos.attach(io: f14, filename: 'tanktop1.jpg')
p7.photos.attach(io: f15, filename: 'tanktop1.jpg')
p8.photos.attach(io: f16, filename: 'tanktop1.jpg')

p1.photos.attach(io: f17, filename: 'tanktop2.jpg')
p2.photos.attach(io: f18, filename: 'tanktop2.jpg')
p3.photos.attach(io: f19, filename: 'tanktop2.jpg')
p4.photos.attach(io: f20, filename: 'tanktop2.jpg')
p5.photos.attach(io: f21, filename: 'tanktop2.jpg')
p6.photos.attach(io: f22, filename: 'tanktop2.jpg')
p7.photos.attach(io: f23, filename: 'tanktop2.jpg')
p8.photos.attach(io: f24, filename: 'tanktop2.jpg')

p9 = Product.create(name: "black shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p10 = Product.create(name: "white shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p11 = Product.create(name: "purple shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p12 = Product.create(name: "gray shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p13 = Product.create(name: "red shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p14 = Product.create(name: "blue shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p15 = Product.create(name: "burgundy shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p16 = Product.create(name: "green shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)

s1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
s2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
s3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
s4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
s5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
s6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
s7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
s8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')

s9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
s10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
s11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
s12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
s13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
s14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
s15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
s16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')

s17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
s18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
s19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
s20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
s21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
s22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
s23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
s24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')

p9.photos.attach(io: s1, filename: 'shirt1.jpeg')
p10.photos.attach(io: s2, filename: 'shirt1.jpeg')
p11.photos.attach(io: s3, filename: 'shirt1.jpeg')
p12.photos.attach(io: s4, filename: 'shirt1.jpeg')
p13.photos.attach(io: s5, filename: 'shirt1.jpeg')
p14.photos.attach(io: s6, filename: 'shirt1.jpeg')
p15.photos.attach(io: s7, filename: 'shirt1.jpeg')
p16.photos.attach(io: s8, filename: 'shirt1.jpeg')

p9.photos.attach(io: s9, filename: 'shirt2.jpeg')
p10.photos.attach(io: s10, filename: 'shirt2.jpeg')
p11.photos.attach(io: s11, filename: 'shirt2.jpeg')
p12.photos.attach(io: s12, filename: 'shirt2.jpeg')
p13.photos.attach(io: s13, filename: 'shirt2.jpeg')
p14.photos.attach(io: s14, filename: 'shirt2.jpeg')
p15.photos.attach(io: s15, filename: 'shirt2.jpeg')
p16.photos.attach(io: s16, filename: 'shirt2.jpeg')

p9.photos.attach(io: s17, filename: 'shirt3.jpeg')
p10.photos.attach(io: s18, filename: 'shirt3.jpeg')
p11.photos.attach(io: s19, filename: 'shirt3.jpeg')
p12.photos.attach(io: s20, filename: 'shirt3.jpeg')
p13.photos.attach(io: s21, filename: 'shirt3.jpeg')
p14.photos.attach(io: s22, filename: 'shirt3.jpeg')
p15.photos.attach(io: s23, filename: 'shirt3.jpeg')
p16.photos.attach(io: s24, filename: 'shirt3.jpeg')

p17 =Product.create(name: "black hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p18 =Product.create(name: "white hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p19 =Product.create(name: "purple hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p20 =Product.create(name: "gray hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p21 =Product.create(name: "red hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p22 =Product.create(name: "blue hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p23 =Product.create(name: "burgundy hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p24 =Product.create(name: "green hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)

h1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
h2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
h3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
h4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
h5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
h6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
h7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
h8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')

h9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
h10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
h11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
h12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
h13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
h14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
h15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
h16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')

h17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
h18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
h19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
h20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
h21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
h22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
h23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
h24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')

p17.photos.attach(io: h1, filename: 'hoodie1.jpeg')
p18.photos.attach(io: h2, filename: 'hoodie1.jpeg')
p19.photos.attach(io: h3, filename: 'hoodie1.jpeg')
p20.photos.attach(io: h4, filename: 'hoodie1.jpeg')
p21.photos.attach(io: h5, filename: 'hoodie1.jpeg')
p22.photos.attach(io: h6, filename: 'hoodie1.jpeg')
p23.photos.attach(io: h7, filename: 'hoodie1.jpeg')
p24.photos.attach(io: h8, filename: 'hoodie1.jpeg')

p17.photos.attach(io: h9, filename: 'hoodie2.jpeg')
p18.photos.attach(io: h10, filename: 'hoodie2.jpeg')
p19.photos.attach(io: h11, filename: 'hoodie2.jpeg')
p20.photos.attach(io: h12, filename: 'hoodie2.jpeg')
p21.photos.attach(io: h13, filename: 'hoodie2.jpeg')
p22.photos.attach(io: h14, filename: 'hoodie2.jpeg')
p23.photos.attach(io: h15, filename: 'hoodie2.jpeg')
p24.photos.attach(io: h16, filename: 'hoodie2.jpeg')

p17.photos.attach(io: h17, filename: 'hoodie3.jpeg')
p18.photos.attach(io: h18, filename: 'hoodie3.jpeg')
p19.photos.attach(io: h19, filename: 'hoodie3.jpeg')
p20.photos.attach(io: h20, filename: 'hoodie3.jpeg')
p21.photos.attach(io: h21, filename: 'hoodie3.jpeg')
p22.photos.attach(io: h22, filename: 'hoodie3.jpeg')
p23.photos.attach(io: h23, filename: 'hoodie3.jpeg')
p24.photos.attach(io: h24, filename: 'hoodie3.jpeg')

p25 =Product.create(name: "black joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p26 =Product.create(name: "white joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p27 =Product.create(name: "purple joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p28 =Product.create(name: "gray joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p29 =Product.create(name: "red joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p30 =Product.create(name: "blue joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p31 =Product.create(name: "burgundy joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p32 =Product.create(name: "camo joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)

j1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
j2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
j3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
j4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
j5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
j6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
j7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
j8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')

j9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
j10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
j11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
j12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
j13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
j14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
j15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
j16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')

j17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
j18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
j19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
j20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
j21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
j22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
j23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
j24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')

p25.photos.attach(io: j1, filename: 'joggers1.jpeg')
p26.photos.attach(io: j2, filename: 'joggers1.jpeg')
p27.photos.attach(io: j3, filename: 'joggers1.jpeg')
p28.photos.attach(io: j4, filename: 'joggers1.jpeg')
p29.photos.attach(io: j5, filename: 'joggers1.jpeg')
p30.photos.attach(io: j6, filename: 'joggers1.jpeg')
p31.photos.attach(io: j7, filename: 'joggers1.jpeg')
p32.photos.attach(io: j8, filename: 'joggers1.jpeg')

p25.photos.attach(io: j9, filename: 'joggers2.jpeg')
p26.photos.attach(io: j10, filename: 'joggers2.jpeg')
p27.photos.attach(io: j11, filename: 'joggers2.jpeg')
p28.photos.attach(io: j12, filename: 'joggers2.jpeg')
p29.photos.attach(io: j13, filename: 'joggers2.jpeg')
p30.photos.attach(io: j14, filename: 'joggers2.jpeg')
p31.photos.attach(io: j15, filename: 'joggers2.jpeg')
p32.photos.attach(io: j16, filename: 'joggers2.jpeg')

p25.photos.attach(io: j17, filename: 'joggers3.jpeg')
p26.photos.attach(io: j18, filename: 'joggers3.jpeg')
p27.photos.attach(io: j19, filename: 'joggers3.jpeg')
p28.photos.attach(io: j20, filename: 'joggers3.jpeg')
p29.photos.attach(io: j21, filename: 'joggers3.jpeg')
p30.photos.attach(io: j22, filename: 'joggers3.jpeg')
p31.photos.attach(io: j23, filename: 'joggers3.jpeg')
p32.photos.attach(io: j24, filename: 'joggers3.jpeg')

p33 =Product.create(name: "black hat", price: 9.95, description: "a black hat", category_id: c5.id)
p34 =Product.create(name: "white hat", price: 9.95, description: "a white hat", category_id: c5.id)
p35 =Product.create(name: "purple hat", price: 9.95, description: "a purple hat", category_id: c5.id)
p36 =Product.create(name: "random hat", price: 9.95, description: "a random hat", category_id: c5.id)
p37 =Product.create(name: "big hat", price: 9.95, description: "a big hat", category_id: c5.id)
p38 =Product.create(name: "small hat", price: 9.95, description: "a small hat", category_id: c5.id)
p39 =Product.create(name: "crazy hat", price: 9.95, description: "a crazy hat", category_id: c5.id)
p40 =Product.create(name: "hat", price: 1.95, description: "just a hat", category_id: c5.id)

hat1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
hat2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
hat3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
hat4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
hat5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
hat6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
hat7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
hat8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')

hat9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
hat10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
hat11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
hat12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
hat13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
hat14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
hat15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
hat16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')

hat17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
hat18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
hat19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
hat20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
hat21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
hat22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
hat23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
hat24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')

p33.photos.attach(io: hat1, filename: 'hat1.jpeg')
p34.photos.attach(io: hat2, filename: 'hat1.jpeg')
p35.photos.attach(io: hat3, filename: 'hat1.jpeg')
p36.photos.attach(io: hat4, filename: 'hat1.jpeg')
p37.photos.attach(io: hat5, filename: 'hat1.jpeg')
p38.photos.attach(io: hat6, filename: 'hat1.jpeg')
p39.photos.attach(io: hat7, filename: 'hat1.jpeg')
p40.photos.attach(io: hat8, filename: 'hat1.jpeg')

p33.photos.attach(io: hat9, filename: 'hat2.jpeg')
p34.photos.attach(io: hat10, filename: 'hat2.jpeg')
p35.photos.attach(io: hat11, filename: 'hat2.jpeg')
p36.photos.attach(io: hat12, filename: 'hat2.jpeg')
p37.photos.attach(io: hat13, filename: 'hat2.jpeg')
p38.photos.attach(io: hat14, filename: 'hat2.jpeg')
p39.photos.attach(io: hat15, filename: 'hat2.jpeg')
p40.photos.attach(io: hat16, filename: 'hat2.jpeg')

p33.photos.attach(io: hat17, filename: 'hat3.jpeg')
p34.photos.attach(io: hat18, filename: 'hat3.jpeg')
p35.photos.attach(io: hat19, filename: 'hat3.jpeg')
p36.photos.attach(io: hat20, filename: 'hat3.jpeg')
p37.photos.attach(io: hat21, filename: 'hat3.jpeg')
p38.photos.attach(io: hat22, filename: 'hat3.jpeg')
p39.photos.attach(io: hat23, filename: 'hat3.jpeg')
p40.photos.attach(io: hat24, filename: 'hat3.jpeg')


p41 =Product.create(name: "black belt", price: 79.95, description: "don't break your back", category_id: c6.id)
p42 =Product.create(name: "purple belt", price: 79.95, description: "don't break your back", category_id: c6.id)
p43 =Product.create(name: "black knee straps", price: 19.95, description: "increase your squat 999 pounds", category_id: c6.id)
p44 =Product.create(name: "red knee straps", price: 19.95, description: "increase your squat 999 pounds", category_id: c6.id)
p45 =Product.create(name: "black knee sleeves", price: 29.95, description: "increase your squat 999 pounds", category_id: c6.id)
p46 =Product.create(name: "red knee sleeves", price: 29.95, description: "increase your squat 999 pounds", category_id: c6.id)
p47 =Product.create(name: "black wrist wraps", price: 19.95, description: "wrist wraps are good", category_id: c6.id)
p48 =Product.create(name: "red wrist wraps", price: 19.95, description: "wrist wraps are good", category_id: c6.id)


g1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
g2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
g3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
g4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
g5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
g6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
g7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
g8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')

g9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
g10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
g11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
g12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
g13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
g14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
g15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
g16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')

g17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
g18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
g19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
g20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
g21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
g22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
g23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
g24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')

p41.photos.attach(io: g1, filename: 'gear1.jpeg')
p42.photos.attach(io: g2, filename: 'gear1.jpeg')
p43.photos.attach(io: g3, filename: 'gear1.jpeg')
p44.photos.attach(io: g4, filename: 'gear1.jpeg')
p45.photos.attach(io: g5, filename: 'gear1.jpeg')
p46.photos.attach(io: g6, filename: 'gear1.jpeg')
p47.photos.attach(io: g7, filename: 'gear1.jpeg')
p48.photos.attach(io: g8, filename: 'gear1.jpeg')

p41.photos.attach(io: g9, filename: 'gear2.jpeg')
p42.photos.attach(io: g10, filename: 'gear2.jpeg')
p43.photos.attach(io: g11, filename: 'gear2.jpeg')
p44.photos.attach(io: g12, filename: 'gear2.jpeg')
p45.photos.attach(io: g13, filename: 'gear2.jpeg')
p46.photos.attach(io: g14, filename: 'gear2.jpeg')
p47.photos.attach(io: g15, filename: 'gear2.jpeg')
p48.photos.attach(io: g16, filename: 'gear2.jpeg')

p41.photos.attach(io: g17, filename: 'gear3.jpeg')
p42.photos.attach(io: g18, filename: 'gear3.jpeg')
p43.photos.attach(io: g19, filename: 'gear3.jpeg')
p44.photos.attach(io: g20, filename: 'gear3.jpeg')
p45.photos.attach(io: g21, filename: 'gear3.jpeg')
p46.photos.attach(io: g22, filename: 'gear3.jpeg')
p47.photos.attach(io: g23, filename: 'gear3.jpeg')
p48.photos.attach(io: g24, filename: 'gear3.jpeg')


Cart.destroy_all

ca1 = Cart.create(user_id: u1.id)
ca2 = Cart.create(user_id: u2.id)
CartItem.destroy_all

Review.destroy_all




