# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'open-uri'

User.destroy_all

u1 = User.create(username: "alex", password: "password")
u2 = User.create(username: "demo-user", password: "password")

Category.destroy_all

c1 = Category.create(name: 'tanks')
c2 = Category.create(name: 'shirts')
c3 = Category.create(name: 'hoodies')
c4 = Category.create(name: 'joggers')
c5 = Category.create(name: 'hats')
c6 = Category.create(name: 'gear')

Product.destroy_all

# TANKS

p1 = Product.create(name: "black tank", price: 29.95, description: "100% aesthetic", category_id: c1.id)
p2 = Product.create(name: "white tank", price: 29.95, description: "100% aesthetic", category_id: c1.id)
p3 = Product.create(name: "red tank", price: 29.95, description: "100% aesthetic", category_id: c1.id)
p4 = Product.create(name: "gray tank", price: 29.95, description: "100% aesthetic", category_id: c1.id)
p5 = Product.create(name: "black stringer", price: 29.95, description: "woah woah woah", category_id: c1.id)
p6 = Product.create(name: "white stringer", price: 29.95, description: "woah woah woah", category_id: c1.id)
p7 = Product.create(name: "black cutoff", price: 29.95, description: "100% aesthetic", category_id: c1.id)
p8 = Product.create(name: "white cutoff", price: 29.95, description: "100% aesthetic", category_id: c1.id)

f1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/blacktank1.jpeg')
f2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/whitetank1.jpeg')
f3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/redtank1.jpeg')
f4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/graytank1.jpeg')
f5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/blackstringer1.jpeg')
f6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/whitestringer1.jpeg')
f7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/blackcutoff1.jpeg')
f8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/whitecutoff1.jpeg')

# f1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
# f2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
# f3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
# f4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
# f5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
# f6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
# f7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')
# f8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ryan.jpg')

f9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/blacktank2.jpeg')
f10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/whitetank2.jpeg')
f11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/redtank2.jpeg')
f12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/graytank2.jpeg')
f13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/blackstringer2.jpeg')
f14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/whitestringer2.jpeg')
f15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/blackcutoff2.jpeg')
f16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/whitecutoff2.jpeg')

# f9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
# f10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
# f11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
# f12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
# f13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
# f14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
# f15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')
# f16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop1.jpeg')

f17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/blacktank3.jpeg')
f18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/whitetank3.jpeg')
f19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/redtank3.jpeg')
f20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/graytank3.jpeg')
f21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/blackstringer3.jpeg')
f22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/whitestringer3.jpeg')
f23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/blackcutoff3.jpeg')
f24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/tanks/whitecutoff3.jpeg')

# f17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
# f18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
# f19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
# f20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
# f21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
# f22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
# f23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')
# f24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/tanktop2.jpeg')

p1.photos.attach(io: f1, filename: 'blacktank1.jpeg')
p2.photos.attach(io: f2, filename: 'whitetank1.jpeg')
p3.photos.attach(io: f3, filename: 'redtank1.jpeg')
p4.photos.attach(io: f4, filename: 'graytank1.jpeg')
p5.photos.attach(io: f5, filename: 'blackstringer1.jpeg')
p6.photos.attach(io: f6, filename: 'whitestringer1.jpeg')
p7.photos.attach(io: f7, filename: 'blackcutoff1.jpeg')
p8.photos.attach(io: f8, filename: 'whitecutoff1.jpeg')

p1.photos.attach(io: f9, filename: 'blacktank2.jpeg')
p2.photos.attach(io: f10, filename: 'whitetank2.jpeg')
p3.photos.attach(io: f11, filename: 'redtank2.jpeg')
p4.photos.attach(io: f12, filename: 'graytank2.jpeg')
p5.photos.attach(io: f13, filename: 'blackstringer2.jpeg')
p6.photos.attach(io: f14, filename: 'whitestringer2.jpeg')
p7.photos.attach(io: f15, filename: 'blackcutoff2.jpeg')
p8.photos.attach(io: f16, filename: 'whitecutoff2.jpeg')

p1.photos.attach(io: f17, filename: 'blacktank2.jpeg')
p2.photos.attach(io: f18, filename: 'whitetank2.jpeg')
p3.photos.attach(io: f19, filename: 'redtank2.jpeg')
p4.photos.attach(io: f20, filename: 'graytank2.jpeg')
p5.photos.attach(io: f21, filename: 'blackstringer2.jpeg')
p6.photos.attach(io: f22, filename: 'whitestringer2.jpeg')
p7.photos.attach(io: f23, filename: 'blackcutoff2.jpeg')
p8.photos.attach(io: f24, filename: 'whitecutoff2.jpeg')

# SHIRTS

p9 = Product.create(name: "black shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p10 = Product.create(name: "white shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p11 = Product.create(name: "purple shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p12 = Product.create(name: "gray shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p13 = Product.create(name: "red shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p14 = Product.create(name: "blue shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p15 = Product.create(name: "burgundy shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
p16 = Product.create(name: "green shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)

s1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/blackshirt1.jpeg')
s2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/whiteshirt1.jpeg')
s3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/purpleshirt1.jpeg')
s4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/grayshirt1.jpeg')
s5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/redshirt1.jpeg')
s6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/blueshirt1.jpeg')
s7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/burgshirt1.jpeg')
s8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/greenshirt1.jpeg')

s9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/blackshirt2.jpeg')
s10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/whiteshirt2.jpeg')
s11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/purpleshirt2.jpeg')
s12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/grayshirt2.jpeg')
s13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/redshirt2.jpeg')
s14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/blueshirt2.jpeg')
s15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/burgshirt2.jpeg')
s16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/greenshirt2.jpeg')

s17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/blackshirt3.jpeg')
s18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/whiteshirt3.jpeg')
s19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/purpleshirt3.jpeg')
s20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/grayshirt3.jpeg')
s21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/redshirt3.jpeg')
s22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/blueshirt3.jpeg')
s23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/burgshirt3.jpeg')
s24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/shirts/greenshirt3.jpeg')

p9.photos.attach(io: s1, filename: 'blackshirt1.jpeg')
p10.photos.attach(io: s2, filename: 'whiteshirt1.jpeg')
p11.photos.attach(io: s3, filename: 'purpleshirt1.jpeg')
p12.photos.attach(io: s4, filename: 'grayshirt1.jpeg')
p13.photos.attach(io: s5, filename: 'redshirt1.jpeg')
p14.photos.attach(io: s6, filename: 'blueshirt1.jpeg')
p15.photos.attach(io: s7, filename: 'burgshirt1.jpeg')
p16.photos.attach(io: s8, filename: 'greenshirt1.jpeg')

p9.photos.attach(io: s9, filename: 'blackshirt2.jpeg')
p10.photos.attach(io: s10, filename: 'whiteshirt2.jpeg')
p11.photos.attach(io: s11, filename: 'purpleshirt2.jpeg')
p12.photos.attach(io: s12, filename: 'grayshirt2.jpeg')
p13.photos.attach(io: s13, filename: 'redshirt2.jpeg')
p14.photos.attach(io: s14, filename: 'blueshirt2.jpeg')
p15.photos.attach(io: s15, filename: 'burgshirt2.jpeg')
p16.photos.attach(io: s16, filename: 'greenshirt2.jpeg')

p9.photos.attach(io: s17, filename: 'blackshirt3.jpeg')
p10.photos.attach(io: s18, filename: 'whiteshirt3.jpeg')
p11.photos.attach(io: s19, filename: 'purpleshirt3.jpeg')
p12.photos.attach(io: s20, filename: 'grayshirt3.jpeg')
p13.photos.attach(io: s21, filename: 'redshirt3.jpeg')
p14.photos.attach(io: s22, filename: 'blueshirt3.jpeg')
p15.photos.attach(io: s23, filename: 'burgshirt3.jpeg')
p16.photos.attach(io: s24, filename: 'greenshirt3.jpeg')

# HOODIES

p17 =Product.create(name: "black hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p18 =Product.create(name: "white hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p19 =Product.create(name: "purple hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p20 =Product.create(name: "gray hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p21 =Product.create(name: "red hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p22 =Product.create(name: "blue hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p23 =Product.create(name: "burgundy hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
p24 =Product.create(name: "green hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)

h1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/blackhoodie1.jpeg')
h2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/whitehoodie1.jpeg')
h3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/purplehoodie1.jpeg')
h4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/grayhoodie1.jpeg')
h5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/redhoodie1.jpeg')
h6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/bluehoodie1.jpeg')
h7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/burgundyhoodie1.jpeg')
h8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/greenhoodie1.jpeg')

h9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/blackhoodie2.jpeg')
h10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/whitehoodie2.jpeg')
h11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/purplehoodie2.jpeg')
h12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/grayhoodie2.jpeg')
h13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/redhoodie2.jpeg')
h14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/bluehoodie2.jpeg')
h15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/burgundyhoodie2.jpeg')
h16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/greenhoodie2.jpeg')

h17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/blackhoodie3.jpeg')
h18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/whitehoodie3.jpeg')
h19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/purplehoodie3.jpeg')
h20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/grayhoodie3.jpeg')
h21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/redhoodie3.jpeg')
h22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/bluehoodie3.jpeg')
h23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/burgundyhoodie3.jpeg')
h24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hoodies/greenhoodie3.jpeg')

p17.photos.attach(io: h1, filename: 'blackhoodie1.jpeg')
p18.photos.attach(io: h2, filename: 'whitehoodie1.jpeg')
p19.photos.attach(io: h3, filename: 'purplehoodie1.jpeg')
p20.photos.attach(io: h4, filename: 'grayhoodie1.jpeg')
p21.photos.attach(io: h5, filename: 'redhoodie1.jpeg')
p22.photos.attach(io: h6, filename: 'bluehoodie1.jpeg')
p23.photos.attach(io: h7, filename: 'burgundyhoodie1.jpeg')
p24.photos.attach(io: h8, filename: 'greenhoodie1.jpeg')

p17.photos.attach(io: h9, filename: 'blackhoodie2.jpeg')
p18.photos.attach(io: h10, filename: 'whitehoodie2.jpeg')
p19.photos.attach(io: h11, filename: 'purplehoodie2.jpeg')
p20.photos.attach(io: h12, filename: 'grayhoodie2.jpeg')
p21.photos.attach(io: h13, filename: 'redhoodie2.jpeg')
p22.photos.attach(io: h14, filename: 'bluehoodie2.jpeg')
p23.photos.attach(io: h15, filename: 'burgundyhoodie2.jpeg')
p24.photos.attach(io: h16, filename: 'greenhoodie2.jpeg')

p17.photos.attach(io: h17, filename: 'blackhoodie3.jpeg')
p18.photos.attach(io: h18, filename: 'whitehoodie3.jpeg')
p19.photos.attach(io: h19, filename: 'purplehoodie3.jpeg')
p20.photos.attach(io: h20, filename: 'grayhoodie3.jpeg')
p21.photos.attach(io: h21, filename: 'redhoodie3.jpeg')
p22.photos.attach(io: h22, filename: 'bluehoodie3.jpeg')
p23.photos.attach(io: h23, filename: 'burgundyhoodie3.jpeg')
p24.photos.attach(io: h24, filename: 'greenhoodie3.jpeg')

p25 =Product.create(name: "black joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p26 =Product.create(name: "white joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p27 =Product.create(name: "purple joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p28 =Product.create(name: "gray joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p29 =Product.create(name: "red joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p30 =Product.create(name: "blue joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p31 =Product.create(name: "burgundy joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
p32 =Product.create(name: "camo joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)

j1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/blackjoggers1.jpeg')
j2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/whitejoggers1.jpeg')
j3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/purplejoggers1.jpeg')
j4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/grayjoggers1.jpeg')
j5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/redjoggers1.jpeg')
j6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/bluejoggers1.jpeg')
j7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/burgundyjoggers1.jpeg')
j8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/camojoggers1.jpeg')

j9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/blackjoggers2.jpeg')
j10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/whitejoggers2.jpeg')
j11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/purplejoggers2.jpeg')
j12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/grayjoggers2.jpeg')
j13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/redjoggers2.jpeg')
j14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/bluejoggers2.jpeg')
j15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/burgundyjoggers2.jpeg')
j16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/camojoggers2.jpeg')

j17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/blackjoggers3.jpeg')
j18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/whitejoggers3.jpeg')
j19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/purplejoggers3.jpeg')
j20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/grayjoggers3.jpeg')
j21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/redjoggers3.jpeg')
j22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/bluejoggers3.jpeg')
j23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/burgundyjoggers3.jpeg')
j24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/joggers/camojoggers3.jpeg')

p25.photos.attach(io: j1, filename: 'blackjoggers1.jpeg')
p26.photos.attach(io: j2, filename: 'whitejoggers1.jpeg')
p27.photos.attach(io: j3, filename: 'purplejoggers1.jpeg')
p28.photos.attach(io: j4, filename: 'grayjoggers1.jpeg')
p29.photos.attach(io: j5, filename: 'redjoggers1.jpeg')
p30.photos.attach(io: j6, filename: 'bluejoggers1.jpeg')
p31.photos.attach(io: j7, filename: 'burgundyjoggers1.jpeg')
p32.photos.attach(io: j8, filename: 'camojoggers1.jpeg')

p25.photos.attach(io: j9, filename: 'blackjoggers2.jpeg')
p26.photos.attach(io: j10, filename: 'whitejoggers2.jpeg')
p27.photos.attach(io: j11, filename: 'purplejoggers2.jpeg')
p28.photos.attach(io: j12, filename: 'grayjoggers2.jpeg')
p29.photos.attach(io: j13, filename: 'redjoggers2.jpeg')
p30.photos.attach(io: j14, filename: 'bluejoggers2.jpeg')
p31.photos.attach(io: j15, filename: 'burgundyjoggers2.jpeg')
p32.photos.attach(io: j16, filename: 'camojoggers2.jpeg')

p25.photos.attach(io: j17, filename: 'blackjoggers3.jpeg')
p26.photos.attach(io: j18, filename: 'whitejoggers3.jpeg')
p27.photos.attach(io: j19, filename: 'purplejoggers3.jpeg')
p28.photos.attach(io: j20, filename: 'grayjoggers3.jpeg')
p29.photos.attach(io: j21, filename: 'redjoggers3.jpeg')
p30.photos.attach(io: j22, filename: 'bluejoggers3.jpeg')
p31.photos.attach(io: j23, filename: 'burgundyjoggers3.jpeg')
p32.photos.attach(io: j24, filename: 'camojoggers3.jpeg')

# HATS

p33 =Product.create(name: "black hat", price: 9.95, description: "a black hat", category_id: c5.id)
p34 =Product.create(name: "white hat", price: 9.95, description: "a white hat", category_id: c5.id)
p35 =Product.create(name: "purple hat", price: 9.95, description: "a purple hat", category_id: c5.id)
p36 =Product.create(name: "random hat", price: 9.95, description: "a random hat", category_id: c5.id)
p37 =Product.create(name: "big hat", price: 9.95, description: "a big hat", category_id: c5.id)
p38 =Product.create(name: "small hat", price: 9.95, description: "a small hat", category_id: c5.id)
p39 =Product.create(name: "crazy hat", price: 9.95, description: "a crazy hat", category_id: c5.id)
p40 =Product.create(name: "hat", price: 1.95, description: "just a hat", category_id: c5.id)

hat1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/blackhat1.jpeg')
hat2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/whitehat1.jpeg')
hat3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/purplehat1.jpeg')
hat4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/randomhat1.jpeg')
hat5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/bighat1.jpeg')
hat6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/smallhat1.jpeg')
hat7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/crazyhat1.jpeg')
hat8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/hat1.jpeg')

hat9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/blackhat2.jpeg')
hat10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/whitehat2.jpeg')
hat11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/purplehat2.jpeg')
hat12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/randomhat2.jpeg')
hat13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/bighat2.jpeg')
hat14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/smallhat2.jpeg')
hat15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/crazyhat2.jpeg')
hat16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/hat2.jpeg')

hat17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/blackhat3.jpeg')
hat18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/whitehat3.jpeg')
hat19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/purplehat3.jpeg')
hat20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/randomhat3.jpeg')
hat21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/bighat3.jpeg')
hat22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/smallhat3.jpeg')
hat23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/crazyhat3.jpeg')
hat24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/hats/hat3.jpeg')

p33.photos.attach(io: hat1, filename: 'blackhat1.jpeg')
p34.photos.attach(io: hat2, filename: 'whitehat1.jpeg')
p35.photos.attach(io: hat3, filename: 'purplehat1.jpeg')
p36.photos.attach(io: hat4, filename: 'randomhat1.jpeg')
p37.photos.attach(io: hat5, filename: 'bighat1.jpeg')
p38.photos.attach(io: hat6, filename: 'smallhat1.jpeg')
p39.photos.attach(io: hat7, filename: 'crazyhat1.jpeg')
p40.photos.attach(io: hat8, filename: 'hat1.jpeg')

p33.photos.attach(io: hat9, filename: 'blackhat2.jpeg')
p34.photos.attach(io: hat10, filename: 'whitehat2.jpeg')
p35.photos.attach(io: hat11, filename: 'purplehat2.jpeg')
p36.photos.attach(io: hat12, filename: 'randomhat2.jpeg')
p37.photos.attach(io: hat13, filename: 'bighat2.jpeg')
p38.photos.attach(io: hat14, filename: 'smallhat2.jpeg')
p39.photos.attach(io: hat15, filename: 'crazyhat2.jpeg')
p40.photos.attach(io: hat16, filename: 'hat2.jpeg')

p33.photos.attach(io: hat17, filename: 'blackhat3.jpeg')
p34.photos.attach(io: hat18, filename: 'whitehat3.jpeg')
p35.photos.attach(io: hat19, filename: 'purplehat3.jpeg')
p36.photos.attach(io: hat20, filename: 'randomhat3.jpeg')
p37.photos.attach(io: hat21, filename: 'bighat3.jpeg')
p38.photos.attach(io: hat22, filename: 'smallhat3.jpeg')
p39.photos.attach(io: hat23, filename: 'crazyhat3.jpeg')
p40.photos.attach(io: hat24, filename: 'hat3.jpeg')

# GEAR 

p41 =Product.create(name: "black belt", price: 79.95, description: "don't break your back", category_id: c6.id)
p42 =Product.create(name: "purple belt", price: 79.95, description: "don't break your back", category_id: c6.id)
p43 =Product.create(name: "black knee straps", price: 19.95, description: "increase your squat 999 pounds", category_id: c6.id)
p44 =Product.create(name: "red knee straps", price: 19.95, description: "increase your squat 999 pounds", category_id: c6.id)
p45 =Product.create(name: "black knee sleeves", price: 29.95, description: "increase your squat 999 pounds", category_id: c6.id)
p46 =Product.create(name: "red knee sleeves", price: 29.95, description: "increase your squat 999 pounds", category_id: c6.id)
p47 =Product.create(name: "black wrist wraps", price: 19.95, description: "wrist wraps are good", category_id: c6.id)
p48 =Product.create(name: "red wrist wraps", price: 19.95, description: "wrist wraps are good", category_id: c6.id)


g1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/blackbelt1.jpeg')
g2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/purplebelt1.jpeg')
g3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/blackkneestraps1.jpeg')
g4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/redkneestraps1.jpeg')
g5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/blackkneesleeves1.jpeg')
g6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/redkneesleeves1.jpeg')
g7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/blackwristwraps1.jpeg')
g8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/redwristwraps1.jpeg')

g9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/blackbelt2.jpeg')
g10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/purplebelt2.jpeg')
g11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/blackkneestraps2.jpeg')
g12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/redkneestraps2.jpeg')
g13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/blackkneesleeves2.jpeg')
g14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/redkneesleeves2.jpeg')
g15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/blackwristwraps2.jpeg')
g16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/redwristwraps2.jpeg')

g17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/blackbelt3.jpeg')
g18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/purplebelt3.jpeg')
g19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/blackkneestraps3.jpeg')
g20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/redkneestraps3.jpeg')
g21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/blackkneesleeves3.jpeg')
g22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/redkneesleeves3.jpeg')
g23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/blackwristwraps3.jpeg')
g24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/ad-fit-gear-product-images/gear/redwristwraps3.jpeg')

p41.photos.attach(io: g1, filename: 'blackbelt1.jpeg')
p42.photos.attach(io: g2, filename: 'purplebelt1.jpeg')
p43.photos.attach(io: g3, filename: 'blackkneestraps1.jpeg')
p44.photos.attach(io: g4, filename: 'redkneestraps1.jpeg')
p45.photos.attach(io: g5, filename: 'blackkneesleeves1.jpeg')
p46.photos.attach(io: g6, filename: 'redkneesleeves1.jpeg')
p47.photos.attach(io: g7, filename: 'blackwristwraps1.jpeg')
p48.photos.attach(io: g8, filename: 'redwristwraps1.jpeg')

p41.photos.attach(io: g9, filename: 'blackbelt2.jpeg')
p42.photos.attach(io: g10, filename: 'purplebelt2.jpeg')
p43.photos.attach(io: g11, filename: 'blackkneestraps2.jpeg')
p44.photos.attach(io: g12, filename: 'redkneestraps2.jpeg')
p45.photos.attach(io: g13, filename: 'blackkneesleeves2.jpeg')
p46.photos.attach(io: g14, filename: 'redkneesleeves2.jpeg')
p47.photos.attach(io: g15, filename: 'blackwristwraps2.jpeg')
p48.photos.attach(io: g16, filename: 'redwristwraps2.jpeg')

p41.photos.attach(io: g17, filename: 'blackbelt3.jpeg')
p42.photos.attach(io: g18, filename: 'purplebelt3.jpeg')
p43.photos.attach(io: g19, filename: 'blackkneestraps3.jpeg')
p44.photos.attach(io: g20, filename: 'redkneestraps3.jpeg')
p45.photos.attach(io: g21, filename: 'blackkneesleeves3.jpeg')
p46.photos.attach(io: g22, filename: 'redkneesleeves3.jpeg')
p47.photos.attach(io: g23, filename: 'blackwristwraps3.jpeg')
p48.photos.attach(io: g24, filename: 'redwristwraps3.jpeg')












# p9 = Product.create(name: "black shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
# p10 = Product.create(name: "white shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
# p11 = Product.create(name: "purple shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
# p12 = Product.create(name: "gray shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
# p13 = Product.create(name: "red shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
# p14 = Product.create(name: "blue shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
# p15 = Product.create(name: "burgundy shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)
# p16 = Product.create(name: "green shirt", price: 29.95, description: "100% aesthetic", category_id: c2.id)

# s1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
# s2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
# s3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
# s4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
# s5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
# s6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
# s7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')
# s8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt1.jpeg')

# s9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
# s10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
# s11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
# s12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
# s13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
# s14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
# s15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')
# s16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt2.jpeg')

# s17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
# s18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
# s19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
# s20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
# s21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
# s22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
# s23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')
# s24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/shirt3.jpeg')

# p9.photos.attach(io: s1, filename: 'shirt1.jpeg')
# p10.photos.attach(io: s2, filename: 'shirt1.jpeg')
# p11.photos.attach(io: s3, filename: 'shirt1.jpeg')
# p12.photos.attach(io: s4, filename: 'shirt1.jpeg')
# p13.photos.attach(io: s5, filename: 'shirt1.jpeg')
# p14.photos.attach(io: s6, filename: 'shirt1.jpeg')
# p15.photos.attach(io: s7, filename: 'shirt1.jpeg')
# p16.photos.attach(io: s8, filename: 'shirt1.jpeg')

# p9.photos.attach(io: s9, filename: 'shirt2.jpeg')
# p10.photos.attach(io: s10, filename: 'shirt2.jpeg')
# p11.photos.attach(io: s11, filename: 'shirt2.jpeg')
# p12.photos.attach(io: s12, filename: 'shirt2.jpeg')
# p13.photos.attach(io: s13, filename: 'shirt2.jpeg')
# p14.photos.attach(io: s14, filename: 'shirt2.jpeg')
# p15.photos.attach(io: s15, filename: 'shirt2.jpeg')
# p16.photos.attach(io: s16, filename: 'shirt2.jpeg')

# p9.photos.attach(io: s17, filename: 'shirt3.jpeg')
# p10.photos.attach(io: s18, filename: 'shirt3.jpeg')
# p11.photos.attach(io: s19, filename: 'shirt3.jpeg')
# p12.photos.attach(io: s20, filename: 'shirt3.jpeg')
# p13.photos.attach(io: s21, filename: 'shirt3.jpeg')
# p14.photos.attach(io: s22, filename: 'shirt3.jpeg')
# p15.photos.attach(io: s23, filename: 'shirt3.jpeg')
# p16.photos.attach(io: s24, filename: 'shirt3.jpeg')

# p17 =Product.create(name: "black hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
# p18 =Product.create(name: "white hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
# p19 =Product.create(name: "purple hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
# p20 =Product.create(name: "gray hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
# p21 =Product.create(name: "red hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
# p22 =Product.create(name: "blue hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
# p23 =Product.create(name: "burgundy hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)
# p24 =Product.create(name: "green hoodie", price: 49.95, description: "hoodie hoodie hoodie", category_id: c3.id)

# h1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
# h2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
# h3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
# h4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
# h5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
# h6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
# h7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')
# h8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie1.jpeg')

# h9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
# h10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
# h11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
# h12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
# h13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
# h14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
# h15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')
# h16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie2.jpeg')

# h17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
# h18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
# h19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
# h20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
# h21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
# h22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
# h23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')
# h24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hoodie3.jpeg')

# p17.photos.attach(io: h1, filename: 'hoodie1.jpeg')
# p18.photos.attach(io: h2, filename: 'hoodie1.jpeg')
# p19.photos.attach(io: h3, filename: 'hoodie1.jpeg')
# p20.photos.attach(io: h4, filename: 'hoodie1.jpeg')
# p21.photos.attach(io: h5, filename: 'hoodie1.jpeg')
# p22.photos.attach(io: h6, filename: 'hoodie1.jpeg')
# p23.photos.attach(io: h7, filename: 'hoodie1.jpeg')
# p24.photos.attach(io: h8, filename: 'hoodie1.jpeg')

# p17.photos.attach(io: h9, filename: 'hoodie2.jpeg')
# p18.photos.attach(io: h10, filename: 'hoodie2.jpeg')
# p19.photos.attach(io: h11, filename: 'hoodie2.jpeg')
# p20.photos.attach(io: h12, filename: 'hoodie2.jpeg')
# p21.photos.attach(io: h13, filename: 'hoodie2.jpeg')
# p22.photos.attach(io: h14, filename: 'hoodie2.jpeg')
# p23.photos.attach(io: h15, filename: 'hoodie2.jpeg')
# p24.photos.attach(io: h16, filename: 'hoodie2.jpeg')

# p17.photos.attach(io: h17, filename: 'hoodie3.jpeg')
# p18.photos.attach(io: h18, filename: 'hoodie3.jpeg')
# p19.photos.attach(io: h19, filename: 'hoodie3.jpeg')
# p20.photos.attach(io: h20, filename: 'hoodie3.jpeg')
# p21.photos.attach(io: h21, filename: 'hoodie3.jpeg')
# p22.photos.attach(io: h22, filename: 'hoodie3.jpeg')
# p23.photos.attach(io: h23, filename: 'hoodie3.jpeg')
# p24.photos.attach(io: h24, filename: 'hoodie3.jpeg')

# p25 =Product.create(name: "black joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
# p26 =Product.create(name: "white joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
# p27 =Product.create(name: "purple joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
# p28 =Product.create(name: "gray joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
# p29 =Product.create(name: "red joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
# p30 =Product.create(name: "blue joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
# p31 =Product.create(name: "burgundy joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)
# p32 =Product.create(name: "camo joggers", price: 49.95, description: "aestheticccccc", category_id: c4.id)

# j1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
# j2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
# j3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
# j4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
# j5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
# j6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
# j7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')
# j8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers1.jpeg')

# j9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
# j10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
# j11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
# j12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
# j13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
# j14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
# j15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')
# j16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers2.jpeg')

# j17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
# j18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
# j19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
# j20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
# j21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
# j22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
# j23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')
# j24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/joggers3.jpeg')

# p25.photos.attach(io: j1, filename: 'joggers1.jpeg')
# p26.photos.attach(io: j2, filename: 'joggers1.jpeg')
# p27.photos.attach(io: j3, filename: 'joggers1.jpeg')
# p28.photos.attach(io: j4, filename: 'joggers1.jpeg')
# p29.photos.attach(io: j5, filename: 'joggers1.jpeg')
# p30.photos.attach(io: j6, filename: 'joggers1.jpeg')
# p31.photos.attach(io: j7, filename: 'joggers1.jpeg')
# p32.photos.attach(io: j8, filename: 'joggers1.jpeg')

# p25.photos.attach(io: j9, filename: 'joggers2.jpeg')
# p26.photos.attach(io: j10, filename: 'joggers2.jpeg')
# p27.photos.attach(io: j11, filename: 'joggers2.jpeg')
# p28.photos.attach(io: j12, filename: 'joggers2.jpeg')
# p29.photos.attach(io: j13, filename: 'joggers2.jpeg')
# p30.photos.attach(io: j14, filename: 'joggers2.jpeg')
# p31.photos.attach(io: j15, filename: 'joggers2.jpeg')
# p32.photos.attach(io: j16, filename: 'joggers2.jpeg')

# p25.photos.attach(io: j17, filename: 'joggers3.jpeg')
# p26.photos.attach(io: j18, filename: 'joggers3.jpeg')
# p27.photos.attach(io: j19, filename: 'joggers3.jpeg')
# p28.photos.attach(io: j20, filename: 'joggers3.jpeg')
# p29.photos.attach(io: j21, filename: 'joggers3.jpeg')
# p30.photos.attach(io: j22, filename: 'joggers3.jpeg')
# p31.photos.attach(io: j23, filename: 'joggers3.jpeg')
# p32.photos.attach(io: j24, filename: 'joggers3.jpeg')

# p33 =Product.create(name: "black hat", price: 9.95, description: "a black hat", category_id: c5.id)
# p34 =Product.create(name: "white hat", price: 9.95, description: "a white hat", category_id: c5.id)
# p35 =Product.create(name: "purple hat", price: 9.95, description: "a purple hat", category_id: c5.id)
# p36 =Product.create(name: "random hat", price: 9.95, description: "a random hat", category_id: c5.id)
# p37 =Product.create(name: "big hat", price: 9.95, description: "a big hat", category_id: c5.id)
# p38 =Product.create(name: "small hat", price: 9.95, description: "a small hat", category_id: c5.id)
# p39 =Product.create(name: "crazy hat", price: 9.95, description: "a crazy hat", category_id: c5.id)
# p40 =Product.create(name: "hat", price: 1.95, description: "just a hat", category_id: c5.id)

# hat1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
# hat2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
# hat3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
# hat4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
# hat5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
# hat6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
# hat7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')
# hat8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat1.jpeg')

# hat9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
# hat10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
# hat11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
# hat12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
# hat13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
# hat14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
# hat15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')
# hat16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat2.jpeg')

# hat17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
# hat18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
# hat19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
# hat20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
# hat21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
# hat22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
# hat23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')
# hat24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/hat3.jpeg')

# p33.photos.attach(io: hat1, filename: 'hat1.jpeg')
# p34.photos.attach(io: hat2, filename: 'hat1.jpeg')
# p35.photos.attach(io: hat3, filename: 'hat1.jpeg')
# p36.photos.attach(io: hat4, filename: 'hat1.jpeg')
# p37.photos.attach(io: hat5, filename: 'hat1.jpeg')
# p38.photos.attach(io: hat6, filename: 'hat1.jpeg')
# p39.photos.attach(io: hat7, filename: 'hat1.jpeg')
# p40.photos.attach(io: hat8, filename: 'hat1.jpeg')

# p33.photos.attach(io: hat9, filename: 'hat2.jpeg')
# p34.photos.attach(io: hat10, filename: 'hat2.jpeg')
# p35.photos.attach(io: hat11, filename: 'hat2.jpeg')
# p36.photos.attach(io: hat12, filename: 'hat2.jpeg')
# p37.photos.attach(io: hat13, filename: 'hat2.jpeg')
# p38.photos.attach(io: hat14, filename: 'hat2.jpeg')
# p39.photos.attach(io: hat15, filename: 'hat2.jpeg')
# p40.photos.attach(io: hat16, filename: 'hat2.jpeg')

# p33.photos.attach(io: hat17, filename: 'hat3.jpeg')
# p34.photos.attach(io: hat18, filename: 'hat3.jpeg')
# p35.photos.attach(io: hat19, filename: 'hat3.jpeg')
# p36.photos.attach(io: hat20, filename: 'hat3.jpeg')
# p37.photos.attach(io: hat21, filename: 'hat3.jpeg')
# p38.photos.attach(io: hat22, filename: 'hat3.jpeg')
# p39.photos.attach(io: hat23, filename: 'hat3.jpeg')
# p40.photos.attach(io: hat24, filename: 'hat3.jpeg')


# p41 =Product.create(name: "black belt", price: 79.95, description: "don't break your back", category_id: c6.id)
# p42 =Product.create(name: "purple belt", price: 79.95, description: "don't break your back", category_id: c6.id)
# p43 =Product.create(name: "black knee straps", price: 19.95, description: "increase your squat 999 pounds", category_id: c6.id)
# p44 =Product.create(name: "red knee straps", price: 19.95, description: "increase your squat 999 pounds", category_id: c6.id)
# p45 =Product.create(name: "black knee sleeves", price: 29.95, description: "increase your squat 999 pounds", category_id: c6.id)
# p46 =Product.create(name: "red knee sleeves", price: 29.95, description: "increase your squat 999 pounds", category_id: c6.id)
# p47 =Product.create(name: "black wrist wraps", price: 19.95, description: "wrist wraps are good", category_id: c6.id)
# p48 =Product.create(name: "red wrist wraps", price: 19.95, description: "wrist wraps are good", category_id: c6.id)


# g1 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
# g2 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
# g3 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
# g4 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
# g5 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
# g6 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
# g7 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')
# g8 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear1.jpeg')

# g9 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
# g10 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
# g11 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
# g12 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
# g13 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
# g14 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
# g15 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')
# g16 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear2.jpeg')

# g17 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
# g18 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
# g19 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
# g20 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
# g21 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
# g22 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
# g23 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')
# g24 = open('https://ad-fit-gear-seeds.s3-us-west-1.amazonaws.com/gear3.jpeg')

# p41.photos.attach(io: g1, filename: 'gear1.jpeg')
# p42.photos.attach(io: g2, filename: 'gear1.jpeg')
# p43.photos.attach(io: g3, filename: 'gear1.jpeg')
# p44.photos.attach(io: g4, filename: 'gear1.jpeg')
# p45.photos.attach(io: g5, filename: 'gear1.jpeg')
# p46.photos.attach(io: g6, filename: 'gear1.jpeg')
# p47.photos.attach(io: g7, filename: 'gear1.jpeg')
# p48.photos.attach(io: g8, filename: 'gear1.jpeg')

# p41.photos.attach(io: g9, filename: 'gear2.jpeg')
# p42.photos.attach(io: g10, filename: 'gear2.jpeg')
# p43.photos.attach(io: g11, filename: 'gear2.jpeg')
# p44.photos.attach(io: g12, filename: 'gear2.jpeg')
# p45.photos.attach(io: g13, filename: 'gear2.jpeg')
# p46.photos.attach(io: g14, filename: 'gear2.jpeg')
# p47.photos.attach(io: g15, filename: 'gear2.jpeg')
# p48.photos.attach(io: g16, filename: 'gear2.jpeg')

# p41.photos.attach(io: g17, filename: 'gear3.jpeg')
# p42.photos.attach(io: g18, filename: 'gear3.jpeg')
# p43.photos.attach(io: g19, filename: 'gear3.jpeg')
# p44.photos.attach(io: g20, filename: 'gear3.jpeg')
# p45.photos.attach(io: g21, filename: 'gear3.jpeg')
# p46.photos.attach(io: g22, filename: 'gear3.jpeg')
# p47.photos.attach(io: g23, filename: 'gear3.jpeg')
# p48.photos.attach(io: g24, filename: 'gear3.jpeg')


Cart.destroy_all

ca1 = Cart.create(user_id: u1.id)
ca2 = Cart.create(user_id: u2.id)
CartItem.destroy_all

Review.destroy_all




